/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEducation: typeof import('./src/components/builder_components/AddEducation.vue')['default']
    AddExperience: typeof import('./src/components/builder_components/AddExperience.vue')['default']
    AddSkill: typeof import('./src/components/builder_components/AddSkill.vue')['default']
    IconRow: typeof import('./src/components/IconRow.vue')['default']
    PDFDownloader: typeof import('./src/services/PDFDownloader')['default']
    Resume: typeof import('./src/components/Resume.vue')['default']
    ResumePreview: typeof import('./src/components/ResumePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLogin: typeof import('./src/components/SocialLogin.vue')['default']
    TemplatePicker: typeof import('./src/components/TemplatePicker.vue')['default']
  }
}
